/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as MesTrajetsIndexImport } from './routes/mes-trajets/index'
import { Route as AjouterUnTrajetIndexImport } from './routes/ajouter-un-trajet/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const MesTrajetsIndexRoute = MesTrajetsIndexImport.update({
  id: '/mes-trajets/',
  path: '/mes-trajets/',
  getParentRoute: () => rootRoute,
} as any)

const AjouterUnTrajetIndexRoute = AjouterUnTrajetIndexImport.update({
  id: '/ajouter-un-trajet/',
  path: '/ajouter-un-trajet/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/ajouter-un-trajet/': {
      id: '/ajouter-un-trajet/'
      path: '/ajouter-un-trajet'
      fullPath: '/ajouter-un-trajet'
      preLoaderRoute: typeof AjouterUnTrajetIndexImport
      parentRoute: typeof rootRoute
    }
    '/mes-trajets/': {
      id: '/mes-trajets/'
      path: '/mes-trajets'
      fullPath: '/mes-trajets'
      preLoaderRoute: typeof MesTrajetsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajouter-un-trajet': typeof AjouterUnTrajetIndexRoute
  '/mes-trajets': typeof MesTrajetsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajouter-un-trajet': typeof AjouterUnTrajetIndexRoute
  '/mes-trajets': typeof MesTrajetsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/ajouter-un-trajet/': typeof AjouterUnTrajetIndexRoute
  '/mes-trajets/': typeof MesTrajetsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ajouter-un-trajet' | '/mes-trajets'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ajouter-un-trajet' | '/mes-trajets'
  id: '__root__' | '/' | '/ajouter-un-trajet/' | '/mes-trajets/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AjouterUnTrajetIndexRoute: typeof AjouterUnTrajetIndexRoute
  MesTrajetsIndexRoute: typeof MesTrajetsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AjouterUnTrajetIndexRoute: AjouterUnTrajetIndexRoute,
  MesTrajetsIndexRoute: MesTrajetsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/ajouter-un-trajet/",
        "/mes-trajets/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/ajouter-un-trajet/": {
      "filePath": "ajouter-un-trajet/index.tsx"
    },
    "/mes-trajets/": {
      "filePath": "mes-trajets/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
